### ISSUE TITLE
m3u8 content may be obsfucated

### ISSUE THREAD

**Issue by Zebartin** [songs18/m3u8_To_MP4#11]
最近遇到一些网站会把m3u8文件中的`xxx.ts`给改成其他后缀名，导致ffmpeg不能识别这些segment，最后不能合成正确的文件。

这个问题是这个包应该考虑的吗？

---

As far as I am concerned, some m3u8 would replace `xxx.ts` with some other suffix, like `xxx.jpeg`, which would lead to the result that ffmpeg fails to recognize the segments seemly with wrong extensions and finally fails to covert them into the video file.

Should this package deal with such a problem?

**Comment by songs18** [comment]
Please give a specific example.

**Comment by Zebartin** [comment]
It is something NSFW though, which I dont feel proper to share here. I would send the example via email.

**Comment by songs18** [comment]
m3u8.to.mp4@hotmail.com

**Comment by songs18** [comment]
I'm sorry I haven't received your email for a long time, and I will close this issue.

If you have a similar question, feel free to open a new issue.
