### ISSUE TITLE
No Audio mp4

### ISSUE THREAD

**Issue by PSPVOLT** [songs18/m3u8_To_MP4#12]
Hello.

Everything works well, but there are problems. There is no sound in the video if m3u8 contains a separate audio track.

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio_aac",NAME="English",DEFAULT=YES,AUTOSELECT=YES,CHANNELS="2",LANGUAGE="rus",URI="site.org"
```

How can this problem be corrected?

**Comment by songs18** [comment]
Thank you for your patience.

A clunky way is to copy the files out before the program empties the temp directory, and then manually download the audio files and merge them.

Thank you for your feedback. I will fix it in the next version.
