### ISSUE TITLE
http referer

### ISSUE THREAD

**Issue by Maydayx2** [songs18/m3u8_To_MP4#3]
Can you add http referer function please

**Comment by songs18** [comment]
Thank you for your proposal. 

I will add it in subsequent git commits. 

It would be great if you could provide an example of using http refer.

**Comment by Maydayx2** [comment]
i would to download videos from here: https://videoseyred.in/embed/e606a61cbch4Tx146291UcQqaa762c12b2

Thank you.

**Comment by songs18** [comment]
Hi, thank you for the your example uri.

In the new commits, i add the customized_http_header parameter, which can override the default request header in the program. 

Hope this solves your issue.
