### ISSUE TITLE
遇到错误

### ISSUE THREAD

**Issue by KimigaiiWuyi** [songs18/m3u8_To_MP4#4]
![23](https://user-images.githubusercontent.com/55526518/145158972-2e678001-0504-4a47-9ffd-0061d9a5998b.png)

此外，doc的示例也有些许错误，直接使用`import m3u8_to_mp4`将会报错，改用了`import m3u8_To_MP4`

**Comment by songs18** [comment]
Thank you for your correction. and i have corrected it to m3u8_To_MP4.

The wheel downloaded from pypi.org is behind the current development progress, so downloading from m3u8 files is not supported.

Please clone from this repository and call the API.
