### ISSUE TITLE
download taptap Video error

### ISSUE THREAD

**Issue by KimigaiiWuyi** [songs18/m3u8_To_MP4#5]
![1](https://user-images.githubusercontent.com/55526518/146483710-2a9b5dd3-33e8-41b7-ac10-17019a62ae78.png)
![Snipaste_2021-12-17_11-21-21](https://user-images.githubusercontent.com/55526518/146483715-fb8638ac-d0a9-471a-be9b-aebfbe4f42b3.png)

**Comment by KimigaiiWuyi** [comment]
Maybe I should customized header to change cookies and refer

**Comment by songs18** [comment]
One way to verify m3u8_uri is to check whether it can be downloaded in a browser that is not commonly used.

If you can't download, try to customize the headers.

Note that to custom headers needs to clone codes from Github. The wheel downloaded from pypi.org is behind the current development progress.
