### ISSUE TITLE
Error processing segments

### ISSUE THREAD

**Issue by Lanimel** [songs18/m3u8_To_MP4#7]
When you set a link of the format **`https://example.m3u8`** everything works fine, but as soon as the parameters appear in the link by type **`https://example.m3u8?e=720&h=23c`** it throws an error while processing

As I understand it, this happens because forbidden characters for names in Windows appear in the link (such as a question mark, for example)

No problem on linux

![0](https://user-images.githubusercontent.com/25524158/166605749-05cbb51d-63fd-4aac-a597-deb742e1c59f.png)

**Comment by songs18** [comment]
Hi,

I read your Traceback carefully. The reason for the OSError is that Windows illegal characters exists in temporary ts path string.
However, the current code does not check the legitimacy of the ts path, which is a flaw.

I will keep this issus open until I fix it.

**Comment by songs18** [comment]
Thanks for your patience, I have fixed this bug.
However, I do not test this function work or not as I don't have a suitable m3u8 uri.
You can clone the latest project and start to download as usual.
I will keep this issue open until your feedback.

**Comment by Lanimel** [comment]
I tested all kinds of links and everything works correctly. It seems the issue can be closed
Thanks
