### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by ALEXDINO7** [songs18/m3u8_To_MP4#9]
when I use this code 

import m3u8_To_MP4

if __name__ == '__main__':
    # 1. Download videos from uri.
    m3u8_To_MP4.multithread_download('http://videoserver.com/playlist.m3u8')

    # 2. Download videos from existing m3u8 files.
    m3u8_To_MP4.multithread_file_download('http://videoserver.com/playlist.m3u8',m3u8_file_path)

    # For compatibility, i reserve this api, but i do not recommend to you again.
    # m3u8_To_MP4.download('http://videoserver.com/playlist.m3u8')

**Comment by songs18** [comment]
The provieded information is limited and I am difficult to say how to solve it. 
Please post the full traceback messages.
I suggest you to check whether the passed mp4 path is valid.

**Comment by songs18** [comment]
This issue was closed due to a long period of time without updates.
